### PR TITLE
Refactor required fields check on Bulk CSV upload

### PR DESCRIPTION
**Pull request by jamazi**
fix https://github.com/Awesome-Technologies/synapse-admin/issues/552

### CODE REVIEW

**Comment by aine-etke** [comment]
That issue already solved by https://github.com/etkecc/synapse-admin/pull/32
So... what are you trying to change with this PR?

**Comment by aine-etke** [comment]
let's consider it refactoring - the updated code looks way better, thank you for contribution!

**Comment by jamazi** [comment]
> That issue already solved by #32 So... what are you trying to change with this PR?

that fix didn't work, I just tried with the latest docker image.

**Comment by aine-etke** [comment]
That's odd... We confirmed it worked on multiple different servers, looks like it was broken again along the way, thank you for contribution!

**Pull request merged**
